modLoader = "javafml"
loaderVersion = "[3,)"
license = "CC BY-NC-SA 4.0"
issueTrackerURL = "https://github.com/st0x0ef/Stellaris/issues"

[[mods]]
modId = "stellaris"
version = "${version}"
displayName = "Stellaris"
authors = "The Stellaris Team"
logoFile = "logo.png"
description = '''
Stellaris introduces an expansive and immersive space exploration experience within the familiar Minecraft universe. Players can discover new planets, moon and galaxies !
'''

[[dependencies.stellaris]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stellaris]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stellaris]]
modId = "architectury"
type = "required"
versionRange = "[12.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "stellaris.mixins.json"
[[mixins]]
config = "stellaris-common.mixins.json"